### PR TITLE
Add Publication Lists

### PR DESCRIPTION
**Pull request by jpfairbanks**
I am adding some automation for generating the publication list from markdown files.

### CODE REVIEW

**Comment by GeorgeR227** [comment]
@jpfairbanks Are there supposed to be images showing up on the Decapodes papers details pages? For example, https://666c87aa1733a4f46a4db57e--glowing-yeot-7d1daa.netlify.app/publications/jocs.

**Comment by jpfairbanks** [comment]
Yeah they are relative paths are probably wrong

**Comment by GeorgeR227** [comment]
The path itself seems fine, looking into it, the problem might be that the `image` label in the title block is not a valid one. It seems like `preprint` and `publication` don't show up either (confirmed by inspecting the web elements) but `doi` does since since this does show up in the quarto docs.

image

Either we can leave it as is for now, since I think the page looks fine even without this or I could try to include the image lower in the page.

**Comment by GeorgeR227** [comment]
I've removed my changes here so I don't hold up the merging. I'll make a new branch with my changes that can be reviewed later.

**Review by GeorgeR227 — APPROVED** [review]

**Pull request merged**
